server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:myservice.p12
    key-store-type: PKCS12
    key-store-password: password

spring:
  application:
    name: file-status-processor
  profiles:
    active: local
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
      fail-fast: true